# Generated by Django 5.1.5 on 2025-01-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='designation',
            field=models.CharField(default='staff', max_length=255),
        ),
    ]
