# Generated by Django 5.1.5 on 2025-03-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_item'),
    ]

    operations = [
    ]
