# Generated by Django 5.1.7 on 2025-03-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_item_id_alter_item_itemname_additem_sale_sellitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
